#!/bin/bash
# Writes ios/Flutter/Secrets.xcconfig from CI environment variables.
# Run before `flutter build ipa` when Secrets.xcconfig is not present locally.
#
# Required env: AIRBRIDGE_SDK_TOKEN
# Optional env: AIRBRIDGE_APP_NAME (overrides flavor default in xcconfig)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_FILE="${SCRIPT_DIR}/../Flutter/Secrets.xcconfig"

if [ -f "$SECRETS_FILE" ]; then
  echo "Secrets.xcconfig already exists — skipping CI generation"
  exit 0
fi

if [ -z "${AIRBRIDGE_SDK_TOKEN:-}" ]; then
  echo "error: AIRBRIDGE_SDK_TOKEN not set and ${SECRETS_FILE} not found"
  echo "Set AIRBRIDGE_SDK_TOKEN in CI or copy ios/Flutter/Secrets.xcconfig.example locally."
  exit 1
fi

{
  echo "// Auto-generated by prepare_ci_secrets.sh — do not commit"
  if [ -n "${AIRBRIDGE_APP_NAME:-}" ]; then
    echo "AIRBRIDGE_APP_NAME=${AIRBRIDGE_APP_NAME}"
  fi
  echo "AIRBRIDGE_SDK_TOKEN=${AIRBRIDGE_SDK_TOKEN}"
} > "$SECRETS_FILE"

echo "Wrote ${SECRETS_FILE} from CI environment variables"
