// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pecha/test/features/mala/mala_sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_pecha/core/error/failures.dart' as _i5;
import 'package:flutter_pecha/features/mala/domain/entities/mala_count.dart'
    as _i6;
import 'package:flutter_pecha/features/mala/domain/usecases/mala_usecases.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CreateUserAccumulatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserAccumulatorUseCase extends _i1.Mock
    implements _i2.CreateUserAccumulatorUseCase {
  MockCreateUserAccumulatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>> call(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [parentId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.MalaCount>>(
                    this,
                    Invocation.method(#call, [parentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>);
}

/// A class which mocks [UpdateUserAccumulatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserAccumulatorUseCase extends _i1.Mock
    implements _i2.UpdateUserAccumulatorUseCase {
  MockUpdateUserAccumulatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>> call(
    _i2.UpdateUserAccumulatorParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.MalaCount>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>);
}

/// A class which mocks [DeleteUserAccumulatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUserAccumulatorUseCase extends _i1.Mock
    implements _i2.DeleteUserAccumulatorUseCase {
  MockDeleteUserAccumulatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> call(String? accumulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [accumulatorId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, [accumulatorId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}

/// A class which mocks [SubmitGroupAccumulatorCountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitGroupAccumulatorCountUseCase extends _i1.Mock
    implements _i2.SubmitGroupAccumulatorCountUseCase {
  MockSubmitGroupAccumulatorCountUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> call(
    _i2.SubmitGroupAccumulatorCountParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}

/// A class which mocks [DeleteGroupAccumulatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteGroupAccumulatorUseCase extends _i1.Mock
    implements _i2.DeleteGroupAccumulatorUseCase {
  MockDeleteGroupAccumulatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> call(
    String? groupAccumulatorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [groupAccumulatorId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, [groupAccumulatorId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
