// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pecha/test/features/mala/mala_counter_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i9;

import 'package:flutter/services.dart' as _i10;
import 'package:flutter/widgets.dart' as _i11;
import 'package:flutter_pecha/core/error/failures.dart' as _i5;
import 'package:flutter_pecha/features/mala/domain/entities/mala_count.dart'
    as _i6;
import 'package:flutter_pecha/features/mala/domain/usecases/mala_usecases.dart'
    as _i2;
import 'package:flutter_pecha/features/mala/presentation/providers/mala_sync_manager.dart'
    as _i8;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetAccumulatorDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAccumulatorDetailUseCase extends _i1.Mock
    implements _i2.GetAccumulatorDetailUseCase {
  MockGetAccumulatorDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>> call(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [parentId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.MalaCount>>(
                    this,
                    Invocation.method(#call, [parentId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.MalaCount>>);
}

/// A class which mocks [MalaSyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMalaSyncManager extends _i1.Mock implements _i8.MalaSyncManager {
  MockMalaSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onGroupCountSynced(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onGroupCountSynced, value),
    returnValueForMissingStub: null,
  );

  @override
  set onPersonalCountSynced(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onPersonalCountSynced, value),
    returnValueForMissingStub: null,
  );

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void onTap({required bool? roundComplete}) => super.noSuchMethod(
    Invocation.method(#onTap, [], {#roundComplete: roundComplete}),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i9.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> flush(_i8.SyncReason? reason) =>
      (super.noSuchMethod(
            Invocation.method(#flush, [reason]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetAccumulator(
    String? presetId, {
    required _i2.DeleteUserAccumulatorUseCase? deleteAccumulator,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetAccumulator,
              [presetId],
              {#deleteAccumulator: deleteAccumulator},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetGroupAccumulator(
    String? groupAccumulatorId, {
    required _i2.DeleteGroupAccumulatorUseCase? deleteGroupAccumulator,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetGroupAccumulator,
              [groupAccumulatorId],
              {#deleteGroupAccumulator: deleteGroupAccumulator},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  bool handleStartBackGesture(_i10.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i10.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> didPushRouteInformation(
    _i11.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i9.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i9.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i9.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i3.Future<_i9.AppExitResponse>.value(
              _i9.AppExitResponse.exit,
            ),
          )
          as _i3.Future<_i9.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DeleteUserAccumulatorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUserAccumulatorUseCase extends _i1.Mock
    implements _i2.DeleteUserAccumulatorUseCase {
  MockDeleteUserAccumulatorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> call(String? accumulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [accumulatorId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, [accumulatorId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
